/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestRouteImport } from './routes/request'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TitleSlugRouteImport } from './routes/title.$slug'
import { Route as SectionKeyRouteImport } from './routes/section.$key'
import { Route as DebugAuthRouteImport } from './routes/debug.auth'
import { Route as BrowseCategoryRouteImport } from './routes/browse.$category'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicClientErrorsRouteImport } from './routes/api/public/client-errors'
import { Route as AuthenticatedAdminVerificationLimitsRouteImport } from './routes/_authenticated/admin.verification-limits'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTutorialRouteImport } from './routes/_authenticated/admin.tutorial'
import { Route as AuthenticatedAdminTitlesRouteImport } from './routes/_authenticated/admin.titles'
import { Route as AuthenticatedAdminTelegramRouteImport } from './routes/_authenticated/admin.telegram'
import { Route as AuthenticatedAdminSyncTraceRouteImport } from './routes/_authenticated/admin.sync-trace'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSlideshowRouteImport } from './routes/_authenticated/admin.slideshow'
import { Route as AuthenticatedAdminShortenersRouteImport } from './routes/_authenticated/admin.shorteners'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminPremiumRouteImport } from './routes/_authenticated/admin.premium'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminInterstitialPerformanceRouteImport } from './routes/_authenticated/admin.interstitial-performance'
import { Route as AuthenticatedAdminHealthRouteImport } from './routes/_authenticated/admin.health'
import { Route as AuthenticatedAdminErrorLogRouteImport } from './routes/_authenticated/admin.error-log'
import { Route as AuthenticatedAdminEpisodeAuditRouteImport } from './routes/_authenticated/admin.episode-audit'
import { Route as AuthenticatedAdminDiagnosticsRouteImport } from './routes/_authenticated/admin.diagnostics'
import { Route as AuthenticatedAdminBulkRouteImport } from './routes/_authenticated/admin.bulk'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as AuthenticatedAdminAlertsRouteImport } from './routes/_authenticated/admin.alerts'
import { Route as AuthenticatedAdminAdsRouteImport } from './routes/_authenticated/admin.ads'
import { Route as AuthenticatedAccountDownloadsRouteImport } from './routes/_authenticated/account.downloads'
import { Route as ApiPublicVTokenRouteImport } from './routes/api/public/v/$token'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramBackfillIngestRouteImport } from './routes/api/public/telegram/backfill-ingest'
import { Route as ApiPublicTelegramBackfillRouteImport } from './routes/api/public/telegram/backfill'
import { Route as ApiPublicSectionKeyRouteImport } from './routes/api/public/section/$key'
import { Route as ApiPublicSTokenRouteImport } from './routes/api/public/s/$token'
import { Route as ApiPublicHooksTelegramResyncRecentRouteImport } from './routes/api/public/hooks/telegram-resync-recent'
import { Route as ApiPublicHooksShortenerAlertsRouteImport } from './routes/api/public/hooks/shortener-alerts'
import { Route as ApiPublicHooksReparseSeriesCronRouteImport } from './routes/api/public/hooks/reparse-series-cron'
import { Route as ApiPublicHooksProcessMessageDeletesRouteImport } from './routes/api/public/hooks/process-message-deletes'
import { Route as ApiPublicHooksProcessDownloadQueueRouteImport } from './routes/api/public/hooks/process-download-queue'
import { Route as ApiPublicHooksMaybeRebuildIndexesRouteImport } from './routes/api/public/hooks/maybe-rebuild-indexes'
import { Route as ApiPublicHooksInterstitialHealthRouteImport } from './routes/api/public/hooks/interstitial-health'
import { Route as ApiPublicHooksInterstitialBeaconRouteImport } from './routes/api/public/hooks/interstitial-beacon'
import { Route as ApiPublicHooksEpisodeAuditAlertsRouteImport } from './routes/api/public/hooks/episode-audit-alerts'

const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSlugRoute = TitleSlugRouteImport.update({
  id: '/title/$slug',
  path: '/title/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SectionKeyRoute = SectionKeyRouteImport.update({
  id: '/section/$key',
  path: '/section/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugAuthRoute = DebugAuthRouteImport.update({
  id: '/debug/auth',
  path: '/debug/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseCategoryRoute = BrowseCategoryRouteImport.update({
  id: '/browse/$category',
  path: '/browse/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClientErrorsRoute = ApiPublicClientErrorsRouteImport.update({
  id: '/api/public/client-errors',
  path: '/api/public/client-errors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminVerificationLimitsRoute =
  AuthenticatedAdminVerificationLimitsRouteImport.update({
    id: '/verification-limits',
    path: '/verification-limits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTutorialRoute =
  AuthenticatedAdminTutorialRouteImport.update({
    id: '/tutorial',
    path: '/tutorial',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTitlesRoute =
  AuthenticatedAdminTitlesRouteImport.update({
    id: '/titles',
    path: '/titles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTelegramRoute =
  AuthenticatedAdminTelegramRouteImport.update({
    id: '/telegram',
    path: '/telegram',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSyncTraceRoute =
  AuthenticatedAdminSyncTraceRouteImport.update({
    id: '/sync-trace',
    path: '/sync-trace',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSlideshowRoute =
  AuthenticatedAdminSlideshowRouteImport.update({
    id: '/slideshow',
    path: '/slideshow',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminShortenersRoute =
  AuthenticatedAdminShortenersRouteImport.update({
    id: '/shorteners',
    path: '/shorteners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPremiumRoute =
  AuthenticatedAdminPremiumRouteImport.update({
    id: '/premium',
    path: '/premium',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInterstitialPerformanceRoute =
  AuthenticatedAdminInterstitialPerformanceRouteImport.update({
    id: '/interstitial-performance',
    path: '/interstitial-performance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHealthRoute =
  AuthenticatedAdminHealthRouteImport.update({
    id: '/health',
    path: '/health',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminErrorLogRoute =
  AuthenticatedAdminErrorLogRouteImport.update({
    id: '/error-log',
    path: '/error-log',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminEpisodeAuditRoute =
  AuthenticatedAdminEpisodeAuditRouteImport.update({
    id: '/episode-audit',
    path: '/episode-audit',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDiagnosticsRoute =
  AuthenticatedAdminDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBulkRoute = AuthenticatedAdminBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAlertsRoute =
  AuthenticatedAdminAlertsRouteImport.update({
    id: '/alerts',
    path: '/alerts',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAdsRoute = AuthenticatedAdminAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAccountDownloadsRoute =
  AuthenticatedAccountDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => AuthenticatedAccountRoute,
  } as any)
const ApiPublicVTokenRoute = ApiPublicVTokenRouteImport.update({
  id: '/api/public/v/$token',
  path: '/api/public/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramBackfillIngestRoute =
  ApiPublicTelegramBackfillIngestRouteImport.update({
    id: '/api/public/telegram/backfill-ingest',
    path: '/api/public/telegram/backfill-ingest',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramBackfillRoute =
  ApiPublicTelegramBackfillRouteImport.update({
    id: '/api/public/telegram/backfill',
    path: '/api/public/telegram/backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSectionKeyRoute = ApiPublicSectionKeyRouteImport.update({
  id: '/api/public/section/$key',
  path: '/api/public/section/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSTokenRoute = ApiPublicSTokenRouteImport.update({
  id: '/api/public/s/$token',
  path: '/api/public/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTelegramResyncRecentRoute =
  ApiPublicHooksTelegramResyncRecentRouteImport.update({
    id: '/api/public/hooks/telegram-resync-recent',
    path: '/api/public/hooks/telegram-resync-recent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksShortenerAlertsRoute =
  ApiPublicHooksShortenerAlertsRouteImport.update({
    id: '/api/public/hooks/shortener-alerts',
    path: '/api/public/hooks/shortener-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReparseSeriesCronRoute =
  ApiPublicHooksReparseSeriesCronRouteImport.update({
    id: '/api/public/hooks/reparse-series-cron',
    path: '/api/public/hooks/reparse-series-cron',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessMessageDeletesRoute =
  ApiPublicHooksProcessMessageDeletesRouteImport.update({
    id: '/api/public/hooks/process-message-deletes',
    path: '/api/public/hooks/process-message-deletes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProcessDownloadQueueRoute =
  ApiPublicHooksProcessDownloadQueueRouteImport.update({
    id: '/api/public/hooks/process-download-queue',
    path: '/api/public/hooks/process-download-queue',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMaybeRebuildIndexesRoute =
  ApiPublicHooksMaybeRebuildIndexesRouteImport.update({
    id: '/api/public/hooks/maybe-rebuild-indexes',
    path: '/api/public/hooks/maybe-rebuild-indexes',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksInterstitialHealthRoute =
  ApiPublicHooksInterstitialHealthRouteImport.update({
    id: '/api/public/hooks/interstitial-health',
    path: '/api/public/hooks/interstitial-health',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksInterstitialBeaconRoute =
  ApiPublicHooksInterstitialBeaconRouteImport.update({
    id: '/api/public/hooks/interstitial-beacon',
    path: '/api/public/hooks/interstitial-beacon',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEpisodeAuditAlertsRoute =
  ApiPublicHooksEpisodeAuditAlertsRouteImport.update({
    id: '/api/public/hooks/episode-audit-alerts',
    path: '/api/public/hooks/episode-audit-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/premium': typeof AuthenticatedPremiumRoute
  '/support': typeof AuthenticatedSupportRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/debug/auth': typeof DebugAuthRoute
  '/section/$key': typeof SectionKeyRoute
  '/title/$slug': typeof TitleSlugRoute
  '/account/downloads': typeof AuthenticatedAccountDownloadsRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/episode-audit': typeof AuthenticatedAdminEpisodeAuditRoute
  '/admin/error-log': typeof AuthenticatedAdminErrorLogRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/interstitial-performance': typeof AuthenticatedAdminInterstitialPerformanceRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/shorteners': typeof AuthenticatedAdminShortenersRoute
  '/admin/slideshow': typeof AuthenticatedAdminSlideshowRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/sync-trace': typeof AuthenticatedAdminSyncTraceRoute
  '/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/admin/titles': typeof AuthenticatedAdminTitlesRoute
  '/admin/tutorial': typeof AuthenticatedAdminTutorialRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verification-limits': typeof AuthenticatedAdminVerificationLimitsRoute
  '/api/public/client-errors': typeof ApiPublicClientErrorsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/episode-audit-alerts': typeof ApiPublicHooksEpisodeAuditAlertsRoute
  '/api/public/hooks/interstitial-beacon': typeof ApiPublicHooksInterstitialBeaconRoute
  '/api/public/hooks/interstitial-health': typeof ApiPublicHooksInterstitialHealthRoute
  '/api/public/hooks/maybe-rebuild-indexes': typeof ApiPublicHooksMaybeRebuildIndexesRoute
  '/api/public/hooks/process-download-queue': typeof ApiPublicHooksProcessDownloadQueueRoute
  '/api/public/hooks/process-message-deletes': typeof ApiPublicHooksProcessMessageDeletesRoute
  '/api/public/hooks/reparse-series-cron': typeof ApiPublicHooksReparseSeriesCronRoute
  '/api/public/hooks/shortener-alerts': typeof ApiPublicHooksShortenerAlertsRoute
  '/api/public/hooks/telegram-resync-recent': typeof ApiPublicHooksTelegramResyncRecentRoute
  '/api/public/s/$token': typeof ApiPublicSTokenRoute
  '/api/public/section/$key': typeof ApiPublicSectionKeyRoute
  '/api/public/telegram/backfill': typeof ApiPublicTelegramBackfillRoute
  '/api/public/telegram/backfill-ingest': typeof ApiPublicTelegramBackfillIngestRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v/$token': typeof ApiPublicVTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/account': typeof AuthenticatedAccountRouteWithChildren
  '/premium': typeof AuthenticatedPremiumRoute
  '/support': typeof AuthenticatedSupportRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/debug/auth': typeof DebugAuthRoute
  '/section/$key': typeof SectionKeyRoute
  '/title/$slug': typeof TitleSlugRoute
  '/account/downloads': typeof AuthenticatedAccountDownloadsRoute
  '/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/episode-audit': typeof AuthenticatedAdminEpisodeAuditRoute
  '/admin/error-log': typeof AuthenticatedAdminErrorLogRoute
  '/admin/health': typeof AuthenticatedAdminHealthRoute
  '/admin/interstitial-performance': typeof AuthenticatedAdminInterstitialPerformanceRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/shorteners': typeof AuthenticatedAdminShortenersRoute
  '/admin/slideshow': typeof AuthenticatedAdminSlideshowRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/sync-trace': typeof AuthenticatedAdminSyncTraceRoute
  '/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/admin/titles': typeof AuthenticatedAdminTitlesRoute
  '/admin/tutorial': typeof AuthenticatedAdminTutorialRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/verification-limits': typeof AuthenticatedAdminVerificationLimitsRoute
  '/api/public/client-errors': typeof ApiPublicClientErrorsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/episode-audit-alerts': typeof ApiPublicHooksEpisodeAuditAlertsRoute
  '/api/public/hooks/interstitial-beacon': typeof ApiPublicHooksInterstitialBeaconRoute
  '/api/public/hooks/interstitial-health': typeof ApiPublicHooksInterstitialHealthRoute
  '/api/public/hooks/maybe-rebuild-indexes': typeof ApiPublicHooksMaybeRebuildIndexesRoute
  '/api/public/hooks/process-download-queue': typeof ApiPublicHooksProcessDownloadQueueRoute
  '/api/public/hooks/process-message-deletes': typeof ApiPublicHooksProcessMessageDeletesRoute
  '/api/public/hooks/reparse-series-cron': typeof ApiPublicHooksReparseSeriesCronRoute
  '/api/public/hooks/shortener-alerts': typeof ApiPublicHooksShortenerAlertsRoute
  '/api/public/hooks/telegram-resync-recent': typeof ApiPublicHooksTelegramResyncRecentRoute
  '/api/public/s/$token': typeof ApiPublicSTokenRoute
  '/api/public/section/$key': typeof ApiPublicSectionKeyRoute
  '/api/public/telegram/backfill': typeof ApiPublicTelegramBackfillRoute
  '/api/public/telegram/backfill-ingest': typeof ApiPublicTelegramBackfillIngestRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v/$token': typeof ApiPublicVTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/_authenticated/account': typeof AuthenticatedAccountRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/debug/auth': typeof DebugAuthRoute
  '/section/$key': typeof SectionKeyRoute
  '/title/$slug': typeof TitleSlugRoute
  '/_authenticated/account/downloads': typeof AuthenticatedAccountDownloadsRoute
  '/_authenticated/admin/ads': typeof AuthenticatedAdminAdsRoute
  '/_authenticated/admin/alerts': typeof AuthenticatedAdminAlertsRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/_authenticated/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/_authenticated/admin/episode-audit': typeof AuthenticatedAdminEpisodeAuditRoute
  '/_authenticated/admin/error-log': typeof AuthenticatedAdminErrorLogRoute
  '/_authenticated/admin/health': typeof AuthenticatedAdminHealthRoute
  '/_authenticated/admin/interstitial-performance': typeof AuthenticatedAdminInterstitialPerformanceRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/shorteners': typeof AuthenticatedAdminShortenersRoute
  '/_authenticated/admin/slideshow': typeof AuthenticatedAdminSlideshowRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/sync-trace': typeof AuthenticatedAdminSyncTraceRoute
  '/_authenticated/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/_authenticated/admin/titles': typeof AuthenticatedAdminTitlesRoute
  '/_authenticated/admin/tutorial': typeof AuthenticatedAdminTutorialRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/verification-limits': typeof AuthenticatedAdminVerificationLimitsRoute
  '/api/public/client-errors': typeof ApiPublicClientErrorsRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/episode-audit-alerts': typeof ApiPublicHooksEpisodeAuditAlertsRoute
  '/api/public/hooks/interstitial-beacon': typeof ApiPublicHooksInterstitialBeaconRoute
  '/api/public/hooks/interstitial-health': typeof ApiPublicHooksInterstitialHealthRoute
  '/api/public/hooks/maybe-rebuild-indexes': typeof ApiPublicHooksMaybeRebuildIndexesRoute
  '/api/public/hooks/process-download-queue': typeof ApiPublicHooksProcessDownloadQueueRoute
  '/api/public/hooks/process-message-deletes': typeof ApiPublicHooksProcessMessageDeletesRoute
  '/api/public/hooks/reparse-series-cron': typeof ApiPublicHooksReparseSeriesCronRoute
  '/api/public/hooks/shortener-alerts': typeof ApiPublicHooksShortenerAlertsRoute
  '/api/public/hooks/telegram-resync-recent': typeof ApiPublicHooksTelegramResyncRecentRoute
  '/api/public/s/$token': typeof ApiPublicSTokenRoute
  '/api/public/section/$key': typeof ApiPublicSectionKeyRoute
  '/api/public/telegram/backfill': typeof ApiPublicTelegramBackfillRoute
  '/api/public/telegram/backfill-ingest': typeof ApiPublicTelegramBackfillIngestRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v/$token': typeof ApiPublicVTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/request'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/trust'
    | '/account'
    | '/admin'
    | '/premium'
    | '/support'
    | '/browse/$category'
    | '/debug/auth'
    | '/section/$key'
    | '/title/$slug'
    | '/account/downloads'
    | '/admin/ads'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/bulk'
    | '/admin/diagnostics'
    | '/admin/episode-audit'
    | '/admin/error-log'
    | '/admin/health'
    | '/admin/interstitial-performance'
    | '/admin/notifications'
    | '/admin/premium'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/shorteners'
    | '/admin/slideshow'
    | '/admin/support'
    | '/admin/sync-trace'
    | '/admin/telegram'
    | '/admin/titles'
    | '/admin/tutorial'
    | '/admin/users'
    | '/admin/verification-limits'
    | '/api/public/client-errors'
    | '/api/public/health'
    | '/admin/'
    | '/api/public/hooks/episode-audit-alerts'
    | '/api/public/hooks/interstitial-beacon'
    | '/api/public/hooks/interstitial-health'
    | '/api/public/hooks/maybe-rebuild-indexes'
    | '/api/public/hooks/process-download-queue'
    | '/api/public/hooks/process-message-deletes'
    | '/api/public/hooks/reparse-series-cron'
    | '/api/public/hooks/shortener-alerts'
    | '/api/public/hooks/telegram-resync-recent'
    | '/api/public/s/$token'
    | '/api/public/section/$key'
    | '/api/public/telegram/backfill'
    | '/api/public/telegram/backfill-ingest'
    | '/api/public/telegram/webhook'
    | '/api/public/v/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/request'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/trust'
    | '/account'
    | '/premium'
    | '/support'
    | '/browse/$category'
    | '/debug/auth'
    | '/section/$key'
    | '/title/$slug'
    | '/account/downloads'
    | '/admin/ads'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/audit'
    | '/admin/bulk'
    | '/admin/diagnostics'
    | '/admin/episode-audit'
    | '/admin/error-log'
    | '/admin/health'
    | '/admin/interstitial-performance'
    | '/admin/notifications'
    | '/admin/premium'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/shorteners'
    | '/admin/slideshow'
    | '/admin/support'
    | '/admin/sync-trace'
    | '/admin/telegram'
    | '/admin/titles'
    | '/admin/tutorial'
    | '/admin/users'
    | '/admin/verification-limits'
    | '/api/public/client-errors'
    | '/api/public/health'
    | '/admin'
    | '/api/public/hooks/episode-audit-alerts'
    | '/api/public/hooks/interstitial-beacon'
    | '/api/public/hooks/interstitial-health'
    | '/api/public/hooks/maybe-rebuild-indexes'
    | '/api/public/hooks/process-download-queue'
    | '/api/public/hooks/process-message-deletes'
    | '/api/public/hooks/reparse-series-cron'
    | '/api/public/hooks/shortener-alerts'
    | '/api/public/hooks/telegram-resync-recent'
    | '/api/public/s/$token'
    | '/api/public/section/$key'
    | '/api/public/telegram/backfill'
    | '/api/public/telegram/backfill-ingest'
    | '/api/public/telegram/webhook'
    | '/api/public/v/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/request'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/trust'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/premium'
    | '/_authenticated/support'
    | '/browse/$category'
    | '/debug/auth'
    | '/section/$key'
    | '/title/$slug'
    | '/_authenticated/account/downloads'
    | '/_authenticated/admin/ads'
    | '/_authenticated/admin/alerts'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/bulk'
    | '/_authenticated/admin/diagnostics'
    | '/_authenticated/admin/episode-audit'
    | '/_authenticated/admin/error-log'
    | '/_authenticated/admin/health'
    | '/_authenticated/admin/interstitial-performance'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/premium'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/shorteners'
    | '/_authenticated/admin/slideshow'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/sync-trace'
    | '/_authenticated/admin/telegram'
    | '/_authenticated/admin/titles'
    | '/_authenticated/admin/tutorial'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/verification-limits'
    | '/api/public/client-errors'
    | '/api/public/health'
    | '/_authenticated/admin/'
    | '/api/public/hooks/episode-audit-alerts'
    | '/api/public/hooks/interstitial-beacon'
    | '/api/public/hooks/interstitial-health'
    | '/api/public/hooks/maybe-rebuild-indexes'
    | '/api/public/hooks/process-download-queue'
    | '/api/public/hooks/process-message-deletes'
    | '/api/public/hooks/reparse-series-cron'
    | '/api/public/hooks/shortener-alerts'
    | '/api/public/hooks/telegram-resync-recent'
    | '/api/public/s/$token'
    | '/api/public/section/$key'
    | '/api/public/telegram/backfill'
    | '/api/public/telegram/backfill-ingest'
    | '/api/public/telegram/webhook'
    | '/api/public/v/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RequestRoute: typeof RequestRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrustRoute: typeof TrustRoute
  BrowseCategoryRoute: typeof BrowseCategoryRoute
  DebugAuthRoute: typeof DebugAuthRoute
  SectionKeyRoute: typeof SectionKeyRoute
  TitleSlugRoute: typeof TitleSlugRoute
  ApiPublicClientErrorsRoute: typeof ApiPublicClientErrorsRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicHooksEpisodeAuditAlertsRoute: typeof ApiPublicHooksEpisodeAuditAlertsRoute
  ApiPublicHooksInterstitialBeaconRoute: typeof ApiPublicHooksInterstitialBeaconRoute
  ApiPublicHooksInterstitialHealthRoute: typeof ApiPublicHooksInterstitialHealthRoute
  ApiPublicHooksMaybeRebuildIndexesRoute: typeof ApiPublicHooksMaybeRebuildIndexesRoute
  ApiPublicHooksProcessDownloadQueueRoute: typeof ApiPublicHooksProcessDownloadQueueRoute
  ApiPublicHooksProcessMessageDeletesRoute: typeof ApiPublicHooksProcessMessageDeletesRoute
  ApiPublicHooksReparseSeriesCronRoute: typeof ApiPublicHooksReparseSeriesCronRoute
  ApiPublicHooksShortenerAlertsRoute: typeof ApiPublicHooksShortenerAlertsRoute
  ApiPublicHooksTelegramResyncRecentRoute: typeof ApiPublicHooksTelegramResyncRecentRoute
  ApiPublicSTokenRoute: typeof ApiPublicSTokenRoute
  ApiPublicSectionKeyRoute: typeof ApiPublicSectionKeyRoute
  ApiPublicTelegramBackfillRoute: typeof ApiPublicTelegramBackfillRoute
  ApiPublicTelegramBackfillIngestRoute: typeof ApiPublicTelegramBackfillIngestRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicVTokenRoute: typeof ApiPublicVTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$slug': {
      id: '/title/$slug'
      path: '/title/$slug'
      fullPath: '/title/$slug'
      preLoaderRoute: typeof TitleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/section/$key': {
      id: '/section/$key'
      path: '/section/$key'
      fullPath: '/section/$key'
      preLoaderRoute: typeof SectionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/auth': {
      id: '/debug/auth'
      path: '/debug/auth'
      fullPath: '/debug/auth'
      preLoaderRoute: typeof DebugAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$category': {
      id: '/browse/$category'
      path: '/browse/$category'
      fullPath: '/browse/$category'
      preLoaderRoute: typeof BrowseCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/client-errors': {
      id: '/api/public/client-errors'
      path: '/api/public/client-errors'
      fullPath: '/api/public/client-errors'
      preLoaderRoute: typeof ApiPublicClientErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/verification-limits': {
      id: '/_authenticated/admin/verification-limits'
      path: '/verification-limits'
      fullPath: '/admin/verification-limits'
      preLoaderRoute: typeof AuthenticatedAdminVerificationLimitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tutorial': {
      id: '/_authenticated/admin/tutorial'
      path: '/tutorial'
      fullPath: '/admin/tutorial'
      preLoaderRoute: typeof AuthenticatedAdminTutorialRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/titles': {
      id: '/_authenticated/admin/titles'
      path: '/titles'
      fullPath: '/admin/titles'
      preLoaderRoute: typeof AuthenticatedAdminTitlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/telegram': {
      id: '/_authenticated/admin/telegram'
      path: '/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AuthenticatedAdminTelegramRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sync-trace': {
      id: '/_authenticated/admin/sync-trace'
      path: '/sync-trace'
      fullPath: '/admin/sync-trace'
      preLoaderRoute: typeof AuthenticatedAdminSyncTraceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/slideshow': {
      id: '/_authenticated/admin/slideshow'
      path: '/slideshow'
      fullPath: '/admin/slideshow'
      preLoaderRoute: typeof AuthenticatedAdminSlideshowRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/shorteners': {
      id: '/_authenticated/admin/shorteners'
      path: '/shorteners'
      fullPath: '/admin/shorteners'
      preLoaderRoute: typeof AuthenticatedAdminShortenersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/premium': {
      id: '/_authenticated/admin/premium'
      path: '/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AuthenticatedAdminPremiumRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/interstitial-performance': {
      id: '/_authenticated/admin/interstitial-performance'
      path: '/interstitial-performance'
      fullPath: '/admin/interstitial-performance'
      preLoaderRoute: typeof AuthenticatedAdminInterstitialPerformanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/health': {
      id: '/_authenticated/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AuthenticatedAdminHealthRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/error-log': {
      id: '/_authenticated/admin/error-log'
      path: '/error-log'
      fullPath: '/admin/error-log'
      preLoaderRoute: typeof AuthenticatedAdminErrorLogRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/episode-audit': {
      id: '/_authenticated/admin/episode-audit'
      path: '/episode-audit'
      fullPath: '/admin/episode-audit'
      preLoaderRoute: typeof AuthenticatedAdminEpisodeAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/diagnostics': {
      id: '/_authenticated/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bulk': {
      id: '/_authenticated/admin/bulk'
      path: '/bulk'
      fullPath: '/admin/bulk'
      preLoaderRoute: typeof AuthenticatedAdminBulkRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/alerts': {
      id: '/_authenticated/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AuthenticatedAdminAlertsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ads': {
      id: '/_authenticated/admin/ads'
      path: '/ads'
      fullPath: '/admin/ads'
      preLoaderRoute: typeof AuthenticatedAdminAdsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/account/downloads': {
      id: '/_authenticated/account/downloads'
      path: '/downloads'
      fullPath: '/account/downloads'
      preLoaderRoute: typeof AuthenticatedAccountDownloadsRouteImport
      parentRoute: typeof AuthenticatedAccountRoute
    }
    '/api/public/v/$token': {
      id: '/api/public/v/$token'
      path: '/api/public/v/$token'
      fullPath: '/api/public/v/$token'
      preLoaderRoute: typeof ApiPublicVTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/backfill-ingest': {
      id: '/api/public/telegram/backfill-ingest'
      path: '/api/public/telegram/backfill-ingest'
      fullPath: '/api/public/telegram/backfill-ingest'
      preLoaderRoute: typeof ApiPublicTelegramBackfillIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/backfill': {
      id: '/api/public/telegram/backfill'
      path: '/api/public/telegram/backfill'
      fullPath: '/api/public/telegram/backfill'
      preLoaderRoute: typeof ApiPublicTelegramBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/section/$key': {
      id: '/api/public/section/$key'
      path: '/api/public/section/$key'
      fullPath: '/api/public/section/$key'
      preLoaderRoute: typeof ApiPublicSectionKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/s/$token': {
      id: '/api/public/s/$token'
      path: '/api/public/s/$token'
      fullPath: '/api/public/s/$token'
      preLoaderRoute: typeof ApiPublicSTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-resync-recent': {
      id: '/api/public/hooks/telegram-resync-recent'
      path: '/api/public/hooks/telegram-resync-recent'
      fullPath: '/api/public/hooks/telegram-resync-recent'
      preLoaderRoute: typeof ApiPublicHooksTelegramResyncRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/shortener-alerts': {
      id: '/api/public/hooks/shortener-alerts'
      path: '/api/public/hooks/shortener-alerts'
      fullPath: '/api/public/hooks/shortener-alerts'
      preLoaderRoute: typeof ApiPublicHooksShortenerAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/reparse-series-cron': {
      id: '/api/public/hooks/reparse-series-cron'
      path: '/api/public/hooks/reparse-series-cron'
      fullPath: '/api/public/hooks/reparse-series-cron'
      preLoaderRoute: typeof ApiPublicHooksReparseSeriesCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-message-deletes': {
      id: '/api/public/hooks/process-message-deletes'
      path: '/api/public/hooks/process-message-deletes'
      fullPath: '/api/public/hooks/process-message-deletes'
      preLoaderRoute: typeof ApiPublicHooksProcessMessageDeletesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/process-download-queue': {
      id: '/api/public/hooks/process-download-queue'
      path: '/api/public/hooks/process-download-queue'
      fullPath: '/api/public/hooks/process-download-queue'
      preLoaderRoute: typeof ApiPublicHooksProcessDownloadQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/maybe-rebuild-indexes': {
      id: '/api/public/hooks/maybe-rebuild-indexes'
      path: '/api/public/hooks/maybe-rebuild-indexes'
      fullPath: '/api/public/hooks/maybe-rebuild-indexes'
      preLoaderRoute: typeof ApiPublicHooksMaybeRebuildIndexesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/interstitial-health': {
      id: '/api/public/hooks/interstitial-health'
      path: '/api/public/hooks/interstitial-health'
      fullPath: '/api/public/hooks/interstitial-health'
      preLoaderRoute: typeof ApiPublicHooksInterstitialHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/interstitial-beacon': {
      id: '/api/public/hooks/interstitial-beacon'
      path: '/api/public/hooks/interstitial-beacon'
      fullPath: '/api/public/hooks/interstitial-beacon'
      preLoaderRoute: typeof ApiPublicHooksInterstitialBeaconRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/episode-audit-alerts': {
      id: '/api/public/hooks/episode-audit-alerts'
      path: '/api/public/hooks/episode-audit-alerts'
      fullPath: '/api/public/hooks/episode-audit-alerts'
      preLoaderRoute: typeof ApiPublicHooksEpisodeAuditAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAccountRouteChildren {
  AuthenticatedAccountDownloadsRoute: typeof AuthenticatedAccountDownloadsRoute
}

const AuthenticatedAccountRouteChildren: AuthenticatedAccountRouteChildren = {
  AuthenticatedAccountDownloadsRoute: AuthenticatedAccountDownloadsRoute,
}

const AuthenticatedAccountRouteWithChildren =
  AuthenticatedAccountRoute._addFileChildren(AuthenticatedAccountRouteChildren)

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAdsRoute: typeof AuthenticatedAdminAdsRoute
  AuthenticatedAdminAlertsRoute: typeof AuthenticatedAdminAlertsRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBulkRoute: typeof AuthenticatedAdminBulkRoute
  AuthenticatedAdminDiagnosticsRoute: typeof AuthenticatedAdminDiagnosticsRoute
  AuthenticatedAdminEpisodeAuditRoute: typeof AuthenticatedAdminEpisodeAuditRoute
  AuthenticatedAdminErrorLogRoute: typeof AuthenticatedAdminErrorLogRoute
  AuthenticatedAdminHealthRoute: typeof AuthenticatedAdminHealthRoute
  AuthenticatedAdminInterstitialPerformanceRoute: typeof AuthenticatedAdminInterstitialPerformanceRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPremiumRoute: typeof AuthenticatedAdminPremiumRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminShortenersRoute: typeof AuthenticatedAdminShortenersRoute
  AuthenticatedAdminSlideshowRoute: typeof AuthenticatedAdminSlideshowRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminSyncTraceRoute: typeof AuthenticatedAdminSyncTraceRoute
  AuthenticatedAdminTelegramRoute: typeof AuthenticatedAdminTelegramRoute
  AuthenticatedAdminTitlesRoute: typeof AuthenticatedAdminTitlesRoute
  AuthenticatedAdminTutorialRoute: typeof AuthenticatedAdminTutorialRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminVerificationLimitsRoute: typeof AuthenticatedAdminVerificationLimitsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAdsRoute: AuthenticatedAdminAdsRoute,
  AuthenticatedAdminAlertsRoute: AuthenticatedAdminAlertsRoute,
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBulkRoute: AuthenticatedAdminBulkRoute,
  AuthenticatedAdminDiagnosticsRoute: AuthenticatedAdminDiagnosticsRoute,
  AuthenticatedAdminEpisodeAuditRoute: AuthenticatedAdminEpisodeAuditRoute,
  AuthenticatedAdminErrorLogRoute: AuthenticatedAdminErrorLogRoute,
  AuthenticatedAdminHealthRoute: AuthenticatedAdminHealthRoute,
  AuthenticatedAdminInterstitialPerformanceRoute:
    AuthenticatedAdminInterstitialPerformanceRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPremiumRoute: AuthenticatedAdminPremiumRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminShortenersRoute: AuthenticatedAdminShortenersRoute,
  AuthenticatedAdminSlideshowRoute: AuthenticatedAdminSlideshowRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminSyncTraceRoute: AuthenticatedAdminSyncTraceRoute,
  AuthenticatedAdminTelegramRoute: AuthenticatedAdminTelegramRoute,
  AuthenticatedAdminTitlesRoute: AuthenticatedAdminTitlesRoute,
  AuthenticatedAdminTutorialRoute: AuthenticatedAdminTutorialRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminVerificationLimitsRoute:
    AuthenticatedAdminVerificationLimitsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RequestRoute: RequestRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrustRoute: TrustRoute,
  BrowseCategoryRoute: BrowseCategoryRoute,
  DebugAuthRoute: DebugAuthRoute,
  SectionKeyRoute: SectionKeyRoute,
  TitleSlugRoute: TitleSlugRoute,
  ApiPublicClientErrorsRoute: ApiPublicClientErrorsRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicHooksEpisodeAuditAlertsRoute: ApiPublicHooksEpisodeAuditAlertsRoute,
  ApiPublicHooksInterstitialBeaconRoute: ApiPublicHooksInterstitialBeaconRoute,
  ApiPublicHooksInterstitialHealthRoute: ApiPublicHooksInterstitialHealthRoute,
  ApiPublicHooksMaybeRebuildIndexesRoute:
    ApiPublicHooksMaybeRebuildIndexesRoute,
  ApiPublicHooksProcessDownloadQueueRoute:
    ApiPublicHooksProcessDownloadQueueRoute,
  ApiPublicHooksProcessMessageDeletesRoute:
    ApiPublicHooksProcessMessageDeletesRoute,
  ApiPublicHooksReparseSeriesCronRoute: ApiPublicHooksReparseSeriesCronRoute,
  ApiPublicHooksShortenerAlertsRoute: ApiPublicHooksShortenerAlertsRoute,
  ApiPublicHooksTelegramResyncRecentRoute:
    ApiPublicHooksTelegramResyncRecentRoute,
  ApiPublicSTokenRoute: ApiPublicSTokenRoute,
  ApiPublicSectionKeyRoute: ApiPublicSectionKeyRoute,
  ApiPublicTelegramBackfillRoute: ApiPublicTelegramBackfillRoute,
  ApiPublicTelegramBackfillIngestRoute: ApiPublicTelegramBackfillIngestRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicVTokenRoute: ApiPublicVTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
