/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RequestRouteImport } from './routes/request'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TitleSlugRouteImport } from './routes/title.$slug'
import { Route as DebugAuthRouteImport } from './routes/debug.auth'
import { Route as BrowseCategoryRouteImport } from './routes/browse.$category'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminVerificationLimitsRouteImport } from './routes/_authenticated/admin.verification-limits'
import { Route as AuthenticatedAdminTutorialRouteImport } from './routes/_authenticated/admin.tutorial'
import { Route as AuthenticatedAdminTitlesRouteImport } from './routes/_authenticated/admin.titles'
import { Route as AuthenticatedAdminTelegramRouteImport } from './routes/_authenticated/admin.telegram'
import { Route as AuthenticatedAdminSyncTraceRouteImport } from './routes/_authenticated/admin.sync-trace'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminRequestsRouteImport } from './routes/_authenticated/admin.requests'
import { Route as AuthenticatedAdminPremiumRouteImport } from './routes/_authenticated/admin.premium'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminDiagnosticsRouteImport } from './routes/_authenticated/admin.diagnostics'
import { Route as AuthenticatedAdminBulkRouteImport } from './routes/_authenticated/admin.bulk'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as ApiPublicVTokenRouteImport } from './routes/api/public/v/$token'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTelegramBackfillRouteImport } from './routes/api/public/telegram/backfill'
import { Route as ApiPublicSTokenRouteImport } from './routes/api/public/s/$token'
import { Route as ApiPublicHooksTelegramResyncRecentRouteImport } from './routes/api/public/hooks/telegram-resync-recent'
import { Route as ApiPublicHooksShortenerAlertsRouteImport } from './routes/api/public/hooks/shortener-alerts'
import { Route as ApiPublicHooksMaybeRebuildIndexesRouteImport } from './routes/api/public/hooks/maybe-rebuild-indexes'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSlugRoute = TitleSlugRouteImport.update({
  id: '/title/$slug',
  path: '/title/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugAuthRoute = DebugAuthRouteImport.update({
  id: '/debug/auth',
  path: '/debug/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseCategoryRoute = BrowseCategoryRouteImport.update({
  id: '/browse/$category',
  path: '/browse/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminVerificationLimitsRoute =
  AuthenticatedAdminVerificationLimitsRouteImport.update({
    id: '/verification-limits',
    path: '/verification-limits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTutorialRoute =
  AuthenticatedAdminTutorialRouteImport.update({
    id: '/tutorial',
    path: '/tutorial',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTitlesRoute =
  AuthenticatedAdminTitlesRouteImport.update({
    id: '/titles',
    path: '/titles',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTelegramRoute =
  AuthenticatedAdminTelegramRouteImport.update({
    id: '/telegram',
    path: '/telegram',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSyncTraceRoute =
  AuthenticatedAdminSyncTraceRouteImport.update({
    id: '/sync-trace',
    path: '/sync-trace',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRequestsRoute =
  AuthenticatedAdminRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPremiumRoute =
  AuthenticatedAdminPremiumRouteImport.update({
    id: '/premium',
    path: '/premium',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDiagnosticsRoute =
  AuthenticatedAdminDiagnosticsRouteImport.update({
    id: '/diagnostics',
    path: '/diagnostics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBulkRoute = AuthenticatedAdminBulkRouteImport.update({
  id: '/bulk',
  path: '/bulk',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicVTokenRoute = ApiPublicVTokenRouteImport.update({
  id: '/api/public/v/$token',
  path: '/api/public/v/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramBackfillRoute =
  ApiPublicTelegramBackfillRouteImport.update({
    id: '/api/public/telegram/backfill',
    path: '/api/public/telegram/backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSTokenRoute = ApiPublicSTokenRouteImport.update({
  id: '/api/public/s/$token',
  path: '/api/public/s/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksTelegramResyncRecentRoute =
  ApiPublicHooksTelegramResyncRecentRouteImport.update({
    id: '/api/public/hooks/telegram-resync-recent',
    path: '/api/public/hooks/telegram-resync-recent',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksShortenerAlertsRoute =
  ApiPublicHooksShortenerAlertsRouteImport.update({
    id: '/api/public/hooks/shortener-alerts',
    path: '/api/public/hooks/shortener-alerts',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksMaybeRebuildIndexesRoute =
  ApiPublicHooksMaybeRebuildIndexesRouteImport.update({
    id: '/api/public/hooks/maybe-rebuild-indexes',
    path: '/api/public/hooks/maybe-rebuild-indexes',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/premium': typeof AuthenticatedPremiumRoute
  '/support': typeof AuthenticatedSupportRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/debug/auth': typeof DebugAuthRoute
  '/title/$slug': typeof TitleSlugRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/sync-trace': typeof AuthenticatedAdminSyncTraceRoute
  '/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/admin/titles': typeof AuthenticatedAdminTitlesRoute
  '/admin/tutorial': typeof AuthenticatedAdminTutorialRoute
  '/admin/verification-limits': typeof AuthenticatedAdminVerificationLimitsRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/maybe-rebuild-indexes': typeof ApiPublicHooksMaybeRebuildIndexesRoute
  '/api/public/hooks/shortener-alerts': typeof ApiPublicHooksShortenerAlertsRoute
  '/api/public/hooks/telegram-resync-recent': typeof ApiPublicHooksTelegramResyncRecentRoute
  '/api/public/s/$token': typeof ApiPublicSTokenRoute
  '/api/public/telegram/backfill': typeof ApiPublicTelegramBackfillRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v/$token': typeof ApiPublicVTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/account': typeof AuthenticatedAccountRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/support': typeof AuthenticatedSupportRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/debug/auth': typeof DebugAuthRoute
  '/title/$slug': typeof TitleSlugRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/sync-trace': typeof AuthenticatedAdminSyncTraceRoute
  '/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/admin/titles': typeof AuthenticatedAdminTitlesRoute
  '/admin/tutorial': typeof AuthenticatedAdminTutorialRoute
  '/admin/verification-limits': typeof AuthenticatedAdminVerificationLimitsRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/maybe-rebuild-indexes': typeof ApiPublicHooksMaybeRebuildIndexesRoute
  '/api/public/hooks/shortener-alerts': typeof ApiPublicHooksShortenerAlertsRoute
  '/api/public/hooks/telegram-resync-recent': typeof ApiPublicHooksTelegramResyncRecentRoute
  '/api/public/s/$token': typeof ApiPublicSTokenRoute
  '/api/public/telegram/backfill': typeof ApiPublicTelegramBackfillRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v/$token': typeof ApiPublicVTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/request': typeof RequestRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/browse/$category': typeof BrowseCategoryRoute
  '/debug/auth': typeof DebugAuthRoute
  '/title/$slug': typeof TitleSlugRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/bulk': typeof AuthenticatedAdminBulkRoute
  '/_authenticated/admin/diagnostics': typeof AuthenticatedAdminDiagnosticsRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/premium': typeof AuthenticatedAdminPremiumRoute
  '/_authenticated/admin/requests': typeof AuthenticatedAdminRequestsRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/sync-trace': typeof AuthenticatedAdminSyncTraceRoute
  '/_authenticated/admin/telegram': typeof AuthenticatedAdminTelegramRoute
  '/_authenticated/admin/titles': typeof AuthenticatedAdminTitlesRoute
  '/_authenticated/admin/tutorial': typeof AuthenticatedAdminTutorialRoute
  '/_authenticated/admin/verification-limits': typeof AuthenticatedAdminVerificationLimitsRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/public/hooks/maybe-rebuild-indexes': typeof ApiPublicHooksMaybeRebuildIndexesRoute
  '/api/public/hooks/shortener-alerts': typeof ApiPublicHooksShortenerAlertsRoute
  '/api/public/hooks/telegram-resync-recent': typeof ApiPublicHooksTelegramResyncRecentRoute
  '/api/public/s/$token': typeof ApiPublicSTokenRoute
  '/api/public/telegram/backfill': typeof ApiPublicTelegramBackfillRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/api/public/v/$token': typeof ApiPublicVTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/request'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/account'
    | '/admin'
    | '/premium'
    | '/support'
    | '/browse/$category'
    | '/debug/auth'
    | '/title/$slug'
    | '/admin/announcements'
    | '/admin/bulk'
    | '/admin/diagnostics'
    | '/admin/notifications'
    | '/admin/premium'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/sync-trace'
    | '/admin/telegram'
    | '/admin/titles'
    | '/admin/tutorial'
    | '/admin/verification-limits'
    | '/admin/'
    | '/api/public/hooks/maybe-rebuild-indexes'
    | '/api/public/hooks/shortener-alerts'
    | '/api/public/hooks/telegram-resync-recent'
    | '/api/public/s/$token'
    | '/api/public/telegram/backfill'
    | '/api/public/telegram/webhook'
    | '/api/public/v/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/request'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/account'
    | '/premium'
    | '/support'
    | '/browse/$category'
    | '/debug/auth'
    | '/title/$slug'
    | '/admin/announcements'
    | '/admin/bulk'
    | '/admin/diagnostics'
    | '/admin/notifications'
    | '/admin/premium'
    | '/admin/requests'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/sync-trace'
    | '/admin/telegram'
    | '/admin/titles'
    | '/admin/tutorial'
    | '/admin/verification-limits'
    | '/admin'
    | '/api/public/hooks/maybe-rebuild-indexes'
    | '/api/public/hooks/shortener-alerts'
    | '/api/public/hooks/telegram-resync-recent'
    | '/api/public/s/$token'
    | '/api/public/telegram/backfill'
    | '/api/public/telegram/webhook'
    | '/api/public/v/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/request'
    | '/reset-password'
    | '/search'
    | '/sitemap.xml'
    | '/_authenticated/account'
    | '/_authenticated/admin'
    | '/_authenticated/premium'
    | '/_authenticated/support'
    | '/browse/$category'
    | '/debug/auth'
    | '/title/$slug'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/bulk'
    | '/_authenticated/admin/diagnostics'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/premium'
    | '/_authenticated/admin/requests'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/sync-trace'
    | '/_authenticated/admin/telegram'
    | '/_authenticated/admin/titles'
    | '/_authenticated/admin/tutorial'
    | '/_authenticated/admin/verification-limits'
    | '/_authenticated/admin/'
    | '/api/public/hooks/maybe-rebuild-indexes'
    | '/api/public/hooks/shortener-alerts'
    | '/api/public/hooks/telegram-resync-recent'
    | '/api/public/s/$token'
    | '/api/public/telegram/backfill'
    | '/api/public/telegram/webhook'
    | '/api/public/v/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  RequestRoute: typeof RequestRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BrowseCategoryRoute: typeof BrowseCategoryRoute
  DebugAuthRoute: typeof DebugAuthRoute
  TitleSlugRoute: typeof TitleSlugRoute
  ApiPublicHooksMaybeRebuildIndexesRoute: typeof ApiPublicHooksMaybeRebuildIndexesRoute
  ApiPublicHooksShortenerAlertsRoute: typeof ApiPublicHooksShortenerAlertsRoute
  ApiPublicHooksTelegramResyncRecentRoute: typeof ApiPublicHooksTelegramResyncRecentRoute
  ApiPublicSTokenRoute: typeof ApiPublicSTokenRoute
  ApiPublicTelegramBackfillRoute: typeof ApiPublicTelegramBackfillRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  ApiPublicVTokenRoute: typeof ApiPublicVTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title/$slug': {
      id: '/title/$slug'
      path: '/title/$slug'
      fullPath: '/title/$slug'
      preLoaderRoute: typeof TitleSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug/auth': {
      id: '/debug/auth'
      path: '/debug/auth'
      fullPath: '/debug/auth'
      preLoaderRoute: typeof DebugAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/$category': {
      id: '/browse/$category'
      path: '/browse/$category'
      fullPath: '/browse/$category'
      preLoaderRoute: typeof BrowseCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/verification-limits': {
      id: '/_authenticated/admin/verification-limits'
      path: '/verification-limits'
      fullPath: '/admin/verification-limits'
      preLoaderRoute: typeof AuthenticatedAdminVerificationLimitsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tutorial': {
      id: '/_authenticated/admin/tutorial'
      path: '/tutorial'
      fullPath: '/admin/tutorial'
      preLoaderRoute: typeof AuthenticatedAdminTutorialRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/titles': {
      id: '/_authenticated/admin/titles'
      path: '/titles'
      fullPath: '/admin/titles'
      preLoaderRoute: typeof AuthenticatedAdminTitlesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/telegram': {
      id: '/_authenticated/admin/telegram'
      path: '/telegram'
      fullPath: '/admin/telegram'
      preLoaderRoute: typeof AuthenticatedAdminTelegramRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/sync-trace': {
      id: '/_authenticated/admin/sync-trace'
      path: '/sync-trace'
      fullPath: '/admin/sync-trace'
      preLoaderRoute: typeof AuthenticatedAdminSyncTraceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/requests': {
      id: '/_authenticated/admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AuthenticatedAdminRequestsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/premium': {
      id: '/_authenticated/admin/premium'
      path: '/premium'
      fullPath: '/admin/premium'
      preLoaderRoute: typeof AuthenticatedAdminPremiumRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/diagnostics': {
      id: '/_authenticated/admin/diagnostics'
      path: '/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bulk': {
      id: '/_authenticated/admin/bulk'
      path: '/bulk'
      fullPath: '/admin/bulk'
      preLoaderRoute: typeof AuthenticatedAdminBulkRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/v/$token': {
      id: '/api/public/v/$token'
      path: '/api/public/v/$token'
      fullPath: '/api/public/v/$token'
      preLoaderRoute: typeof ApiPublicVTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/backfill': {
      id: '/api/public/telegram/backfill'
      path: '/api/public/telegram/backfill'
      fullPath: '/api/public/telegram/backfill'
      preLoaderRoute: typeof ApiPublicTelegramBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/s/$token': {
      id: '/api/public/s/$token'
      path: '/api/public/s/$token'
      fullPath: '/api/public/s/$token'
      preLoaderRoute: typeof ApiPublicSTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/telegram-resync-recent': {
      id: '/api/public/hooks/telegram-resync-recent'
      path: '/api/public/hooks/telegram-resync-recent'
      fullPath: '/api/public/hooks/telegram-resync-recent'
      preLoaderRoute: typeof ApiPublicHooksTelegramResyncRecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/shortener-alerts': {
      id: '/api/public/hooks/shortener-alerts'
      path: '/api/public/hooks/shortener-alerts'
      fullPath: '/api/public/hooks/shortener-alerts'
      preLoaderRoute: typeof ApiPublicHooksShortenerAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/maybe-rebuild-indexes': {
      id: '/api/public/hooks/maybe-rebuild-indexes'
      path: '/api/public/hooks/maybe-rebuild-indexes'
      fullPath: '/api/public/hooks/maybe-rebuild-indexes'
      preLoaderRoute: typeof ApiPublicHooksMaybeRebuildIndexesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminBulkRoute: typeof AuthenticatedAdminBulkRoute
  AuthenticatedAdminDiagnosticsRoute: typeof AuthenticatedAdminDiagnosticsRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminPremiumRoute: typeof AuthenticatedAdminPremiumRoute
  AuthenticatedAdminRequestsRoute: typeof AuthenticatedAdminRequestsRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminSyncTraceRoute: typeof AuthenticatedAdminSyncTraceRoute
  AuthenticatedAdminTelegramRoute: typeof AuthenticatedAdminTelegramRoute
  AuthenticatedAdminTitlesRoute: typeof AuthenticatedAdminTitlesRoute
  AuthenticatedAdminTutorialRoute: typeof AuthenticatedAdminTutorialRoute
  AuthenticatedAdminVerificationLimitsRoute: typeof AuthenticatedAdminVerificationLimitsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminBulkRoute: AuthenticatedAdminBulkRoute,
  AuthenticatedAdminDiagnosticsRoute: AuthenticatedAdminDiagnosticsRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminPremiumRoute: AuthenticatedAdminPremiumRoute,
  AuthenticatedAdminRequestsRoute: AuthenticatedAdminRequestsRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminSyncTraceRoute: AuthenticatedAdminSyncTraceRoute,
  AuthenticatedAdminTelegramRoute: AuthenticatedAdminTelegramRoute,
  AuthenticatedAdminTitlesRoute: AuthenticatedAdminTitlesRoute,
  AuthenticatedAdminTutorialRoute: AuthenticatedAdminTutorialRoute,
  AuthenticatedAdminVerificationLimitsRoute:
    AuthenticatedAdminVerificationLimitsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  RequestRoute: RequestRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BrowseCategoryRoute: BrowseCategoryRoute,
  DebugAuthRoute: DebugAuthRoute,
  TitleSlugRoute: TitleSlugRoute,
  ApiPublicHooksMaybeRebuildIndexesRoute:
    ApiPublicHooksMaybeRebuildIndexesRoute,
  ApiPublicHooksShortenerAlertsRoute: ApiPublicHooksShortenerAlertsRoute,
  ApiPublicHooksTelegramResyncRecentRoute:
    ApiPublicHooksTelegramResyncRecentRoute,
  ApiPublicSTokenRoute: ApiPublicSTokenRoute,
  ApiPublicTelegramBackfillRoute: ApiPublicTelegramBackfillRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  ApiPublicVTokenRoute: ApiPublicVTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
